/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as badgeTypeControllers from "./badgeTypeControllers";
export * as interfaces from "./interfaces";
export { TheBadge__factory } from "./TheBadge__factory";
