/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as badgeTypeControllers from "./badgeTypeControllers";
export type { badgeTypeControllers };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { TheBadge } from "./TheBadge";
