/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IBadgeController__factory } from "./IBadgeController__factory";
export { ILightGTCRFactory__factory } from "./ILightGTCRFactory__factory";
export { ILightGeneralizedTCR__factory } from "./ILightGeneralizedTCR__factory";
export { ITheBadge__factory } from "./ITheBadge__factory";
