/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBadgeController } from "./IBadgeController";
export type { ILightGTCRFactory } from "./ILightGTCRFactory";
export type { ILightGeneralizedTCR } from "./ILightGeneralizedTCR";
export type { ITheBadge } from "./ITheBadge";
