/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace ITheBadge {
  export type BadgeStruct = {
    status: PromiseOrValue<BigNumberish>;
    dueDate: PromiseOrValue<BigNumberish>;
  };

  export type BadgeStructOutput = [number, BigNumber] & {
    status: number;
    dueDate: BigNumber;
  };
}

export interface ITheBadgeInterface extends utils.Interface {
  functions: {
    "badge(uint256,address)": FunctionFragment;
    "updateBadgeStatus(uint256,address,uint8)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "badge" | "updateBadgeStatus"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "badge",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateBadgeStatus",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;

  decodeFunctionResult(functionFragment: "badge", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateBadgeStatus",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ITheBadge extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ITheBadgeInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    badge(
      _badgeId: PromiseOrValue<BigNumberish>,
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[ITheBadge.BadgeStructOutput]>;

    updateBadgeStatus(
      badgeId: PromiseOrValue<BigNumberish>,
      badgeOwner: PromiseOrValue<string>,
      status: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  badge(
    _badgeId: PromiseOrValue<BigNumberish>,
    _account: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<ITheBadge.BadgeStructOutput>;

  updateBadgeStatus(
    badgeId: PromiseOrValue<BigNumberish>,
    badgeOwner: PromiseOrValue<string>,
    status: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    badge(
      _badgeId: PromiseOrValue<BigNumberish>,
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<ITheBadge.BadgeStructOutput>;

    updateBadgeStatus(
      badgeId: PromiseOrValue<BigNumberish>,
      badgeOwner: PromiseOrValue<string>,
      status: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    badge(
      _badgeId: PromiseOrValue<BigNumberish>,
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    updateBadgeStatus(
      badgeId: PromiseOrValue<BigNumberish>,
      badgeOwner: PromiseOrValue<string>,
      status: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    badge(
      _badgeId: PromiseOrValue<BigNumberish>,
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    updateBadgeStatus(
      badgeId: PromiseOrValue<BigNumberish>,
      badgeOwner: PromiseOrValue<string>,
      status: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
