/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc792 from "./erc-792";
export type { erc792 };
import type * as openzeppelinContractsUpgradeable from "./openzeppelin-contracts-upgradeable";
export type { openzeppelinContractsUpgradeable };
