name: "Tests - PR"

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
    branches:
      - main
      - develop

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge tests
        run: |
          forge test -vvv --fork-url --fork-url https://rpc.ankr.com/eth_sepolia --fork-block-number 4044182
        id: test

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build
